<?php

declare(strict_types=1);

namespace valres\toolbox\behavior\item\vanilla;

use pocketmine\block\Block;
use pocketmine\item\Item;
use pocketmine\item\ItemIdentifier;
use valres\toolbox\behavior\attribute\DataDrivenItem;
use valres\toolbox\behavior\block\AutoGeneratedBlockItem;

#[DataDrivenItem]
final class DefaultBlockItem extends Item implements AutoGeneratedBlockItem {
    public function __construct(
        ItemIdentifier $identifier,
        string $name,
        private readonly Block $block
    ) {
        parent::__construct($identifier, $name);
    }

    public function getBlock(?int $clickedFace = null): Block {
        return clone $this->block;
    }
}
